channels:
  - defaults
dependencies:
  - python=3.9
  - pip>=20.3.3
  - pip:
      - matplotlib>=3.3.3
      - numpy>=1.20
      - astropy>=4.2
      - tqdm
      - ads
      - pandas
      - pylatexenc
      - gitpython
      - scipy
