name: article

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  showyourwork:
    runs-on: ubuntu-latest
    name: Build the article PDF
    concurrency: showyourwork-${{ github.ref }}
    env:
      ADS_DEV_KEY: ${{ secrets.ADS_DEV_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Checkout astropy
        uses: actions/checkout@v3
        with:
          repository: astropy/astropy
          fetch-depth: 0
          path: astropy

      - name: Build the article PDF
        id: build
        uses: ./showyourwork/showyourwork-action
        with:
          article-cache-number: null  # disable caching
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
          ASTROPY_REPO_PATH: /home/runner/work/astropy-v5.0-paper/astropy-v5.0-paper/astropy

      - uses: actions/upload-artifact@v3
        with:
          name: built paper
          path: ms.pdf
